---
- hosts: all
  become: true
  remote_user: root
  tasks:
    - name: install httpd service
      yum: name=httpd state=latest
    - name: download configuration file
      get_url:
        url: http://rhgls/httpd.conf.template
        dest: /etc/http/conf/httpd.conf
    - name: adding content ussinf lineinfile module
      lineinfile:
        dest: /var/www/html/index.html
        line: "Hello from {{ item }}"
      with_items:
        - node1
        - node2
        - node3
        - node4
    - name: start httpd service
      service: name=httpd state=started enabled=yes
